version: '3.8'

services:
  frontend:
    container_name: frontend-docker
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - account-api-net

  backend:
    container_name: backend-docker
    build: ./backend
    restart: always
    ports:
      - '8080:8080'
    networks:
      - account-api-net
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

networks:
  account-api-net:
    driver: bridge
