version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    container_name: frontend-docker
    restart: always
    depends_on:
      - backend
    networks:
      - docker-net

  backend:
    container_name: backend-docker
    restart: always
    build: ./backend
    ports:
      - '8080:8080'
    networks:
      - docker-net
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

networks:
  docker-net:
    driver: bridge
