# spring boot configuration
spring:
  profiles:
    active: production
  application:
    name: account-api
  main:
    banner-mode: console
  jackson:
    date-format: "dd.MM.yyyy"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:${DB_NAME};DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=false
    username: ${DB_USERNAME}
    password: # leave password field empty for H2 database Server Mode connection
  flyway:
    enabled: true
    placeholderReplacement: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: 'true'
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework: error
    org.hibernate: error
    com.github.yildizmy: debug
  file:
    name: './logs/application.log'

# server configuration
server:
  port: 8080
  # exception handling
  error:
    include-stacktrace: on_param
    include-exception: 'true'
    include-binding-errors: always
    include-message: always

# custom properties
reflecting:
  trace: 'true'
